name: Build and Deploy
permissions:
  contents: write
on: #触发条件
  push:
    branches:
      - master #推送到master 就触发
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      # 安装node
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.com/

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9
          run_install: false

      # 构建
      - name: Deploy 🔧
        run: |
          pnpm install --no-frozen-lockfile
          pnpm build:prod
          cd dist
          touch README.md .nojekyll

      # 部署
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist
