# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Build And Deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['master']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.com/

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        id: pnpm-install
        with:
          version: 9
          run_install: false

  # Deployment job
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy 🔧
        run: |
          pnpm install --no-frozen-lockfile
          sed -i "s#VITE_APP_CONTEXT_PATH = /#VITE_APP_CONTEXT_PATH = /spyro-vue-admin/#g" $(pwd)/.env.production
          pnpm build
          cd dist
          touch README.md .nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          clean: true
